name: Build Arch ISO

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        privileged: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Docker CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Run Arch ISO Builder in Docker
        run: |
          docker run --rm -v $PWD:/build -w /build archlinux bash -c "
            pacman -Sy --noconfirm arch-install-scripts mkinitcpio squashfs-tools xorriso syslinux &&
            chmod +x build.sh profiles/default/post_install.sh &&
            ./build.sh
          "
