name: Build Arch Linux ISO

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Install dependencies
        run: |
          pacman -Sy --noconfirm archiso git base-devel

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare custom profile
        run: |
          mkdir -p /archlive/custom
          cp -r ./profile/* /archlive/custom/

      - name: Build ISO
        run: |
          mkarchiso -v -w /archlive/work -o /archlive/out /archlive/custom

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: archlinux-custom-iso
          path: /archlive/out/*.iso
