name: Build Arch ISO

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest
    
    container:
      image: archlinux:latest
   
          
        

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Docker CLI
        run: |
          sudo apt-get update
          pacman -Sy --noconfirm base
          sudo apt-get install -y docker-ce docker-ce-cli

      - name: Run Arch ISO Builder in Docker
        run: |
          docker run --rm -v $PWD:/build -w /build archlinux bash -c "
            pacman -Sy --noconfirm arch-install-scripts mkinitcpio squashfs-tools xorriso syslinux &&
            chmod +x build.sh profiles/default/post_install.sh &&
            ./build.sh
          "
